version: "3.7"
services:
  localstack:
    image: localstack/localstack:0.11.4
    ports: [ "4566-4599:4566-4599" ]
    environment:
      - DEBUG=1
      - SERVICES=sqs,sns,dynamodb,apigateway,ssm,lambda,s3,cloudformation,sts,iam,cloudwatch,logs,events,dynamodbstreams
      - DEFAULT_REGION=eu-west-2
      - LAMBDA_EXECUTOR=docker-reuse
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - '/private/tmp/localstack:/tmp/localstack'
      - "/var/run/docker.sock:/var/run/docker.sock"